GET http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUzNjEwMjF9.Fq9QmsRV6kHcfjgMmGFuLOe3wGEk7iThw8-dHn28Psg

###

GET http://localhost:3000/products/2.json
Content-Type: application/json

###

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "A Fig", "price": 0, "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/02/figs-2056729.jpg?webp=true&quality=90&resize=408%2C370", "description": "Sweet and Wonderous"
}

###

DELETE http://localhost:3000/products/12.json
Content-Type: application/json

###

PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "price": 2
}

###

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Tanner",
  "email": "Tanner@test.com",
  "password": "tanner",
  "password_confirmation": "tanner"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "Shane@test.com",
  "password": "admin1234"
}

### order create

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNjg2MzZ9.stdFaGFZ9QQxRT_MH8Yb-iM4aWGnaKlPYTUn7I8Mf_w

{
  "product_id": 10,
  "quantity": 12
}

# change url to image_url

### get request

GET http://localhost:3000/orders/2.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNjg2MzZ9.stdFaGFZ9QQxRT_MH8Yb-iM4aWGnaKlPYTUn7I8Mf_w